### ISSUE TITLE
Connect the Arduino directly to the PixHawk

### ISSUE THREAD

**Issue by AlexisTM** [AlexisTM/Indoor_Position_lasers#1]
@ajaybhatt003 Refering to :  https://github.com/AlexisTM/Indoor_Position_lasers/commit/5a654492d9ed4f3c446e3a4e7029cab70af3cda6#commitcomment-18876297

Hello @ajaybhatt003, the Arduino script you see here is a ROS connection. It means the PixHawk and the Arduino are connected to an onboard computer (Odroid XU4, could be a RPi3). The Arduino sends the data to the onboard computer via a ROS library (rosserial), the computer compute (in this case : the position of the multicopter) and then, the onboard computer sends the data to the Pixhawk (the position). 

At first we tried to connect directly the Arduino to the PixHawk, which is possible in different ways. 
- MAVLink : Send a [MAVLink](https://github.com/mavlink/mavlink) compatible message on the serial port, eventually create a new message if you need to send custom data, on port TELEM 1. (connect the RX of the Arduino to the TX of the Pixhawk and the opposite) 

> This require a lot of memory on the Arduino (I don't remember the exact amount)
- Serialize and Send custom frames to the Pixhawk and deserialize on the PixHawk. 

> You will have to find a library or create a frame, like "0xFF, N bytes of data, CRC" and create a PixHawk script to handle it.

**Comment by AlexisTM** [comment]
Here is an [example of Pixhawk to Arduino via MAVLINK](https://raw.githubusercontent.com/AlexisTM/Thesis-Lasers-Positionning-system/master/3.Receive_Attitude_LCD/3.Receive_Attitude_LCD.ino?token=AGp06FPj9K5VolVeUD4tO8yIiabpCdeBks5X0rH0wA%3D%3D) code. This was the first tests to communicate with the Pixhawk. If you need more flexibility, I advise you to use ROS & Mavros (ROS Library). Orelse, check the mavros code if you only need that module and ignore the ROS integration.

It shows the attitude of the multicopter on a LCD screen. The main idea of Mavlink is the same for sending.

**Receive** : Check the input buffer, if the idea correspond to theone you want, unpack the message, else drop the message.

**Send** : Pack the message, send it via the serial port.

Connexions : 
Arduino RX to TX Pixhawk
Arduino TX to RX Pixhawk
Arduino GND to GND Pixhawk

> Caution : The Pixhawk accepts 3v3 UART levels, you should use a level shifter. Note that the Pixhawk is 5V tolerant.

**Comment by KochC** [comment]
The example is just a File containing Error 404? :/

**Comment by AlexisTM** [comment]
Indeed, I deleted that repo a while ago as it was basically a "keep track of things until we are sure we don't need them anymore" 

Here is another example from another project: https://github.com/diydrones/MinimOSD-Extra/blob/master/MinimOsd-Extra/MAVLink.ino

NOTE: To achieve a link to the Pixhawk you need to send MAVLink packets according to your will and also a MAVLink heartbeat to keep the connexion.
